apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-app-worker-config
  labels:
    app.kubernetes.io/name: temporal-app-worker
data:
  TEMPORAL_ADDRESS: temporal-frontend.temporal.svc.cluster.local:7233
  TEMPORAL_NAMESPACE: default
  TEMPORAL_TASK_QUEUE: sample-task-queue
  LOG_LEVEL: info
