apiVersion: v1
kind: Service
metadata:
  name: temporal-worker
  labels:
    app.kubernetes.io/name: temporal-worker
spec:
  selector:
    app.kubernetes.io/name: temporal-worker
  ports:
    - name: http
      port: 8080
      targetPort: http
  type: ClusterIP
